"""stage11_add_insight_run_metadata

Revision ID: f893dcf4c86d
Revises: 1228560be2d2
Create Date: 2026-09-23 20:56:28.219641

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f893dcf4c86d'
down_revision: str | None = '1228560be2d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights', sa.Column('run_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insights', 'run_metadata')
    # ### end Alembic commands ###