"""stage02_nine_tables

Revision ID: 080803e99048
Revises: 
Create Date: 2026-09-23 19:48:37.569855

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '080803e99048'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('budget_total', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('budget_used', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_projects_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('location', sa.String(length=1024), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_data_sources_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources'))
    )
    op.create_index(op.f('ix_data_sources_project_id'), 'data_sources', ['project_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_run_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('current_phase', sa.String(length=32), nullable=True),
    sa.Column('phase_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('cost_actual', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('run_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("agent_runs.status IN ('queued', 'running', 'completed', 'partial_success', 'failed', 'timeout', 'cancelled')", name=op.f('ck_agent_runs_agent_run_status')),
    sa.ForeignKeyConstraint(['parent_run_id'], ['agent_runs.id'], name=op.f('fk_agent_runs_parent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_agent_runs_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_agent_runs_source_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_idempotency_key'), 'agent_runs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_agent_runs_parent_run_id'), 'agent_runs', ['parent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_project_id'), 'agent_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_source_id'), 'agent_runs', ['source_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('event_groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('group_key', sa.String(length=128), nullable=False),
    sa.Column('template', sa.Text(), nullable=True),
    sa.Column('time_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_event_groups_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_event_groups_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_groups')),
    sa.UniqueConstraint('project_id', 'source_id', 'group_key', name='project_source_group_key')
    )
    op.create_index(op.f('ix_event_groups_project_id'), 'event_groups', ['project_id'], unique=False)
    op.create_index(op.f('ix_event_groups_source_id'), 'event_groups', ['source_id'], unique=False)
    op.create_index(op.f('ix_event_groups_time_start'), 'event_groups', ['time_start'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("events.event_type IN ('log', 'metric')", name=op.f('ck_events_event_type')),
    sa.CheckConstraint("events.severity IN ('high', 'medium', 'low')", name=op.f('ck_events_event_severity')),
    sa.ForeignKeyConstraint(['group_id'], ['event_groups.id'], name=op.f('fk_events_group_id_event_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='fk_events_incident_id_incidents', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_events_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_events_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_group_id'), 'events', ['group_id'], unique=False)
    op.create_index(op.f('ix_events_incident_id'), 'events', ['incident_id'], unique=False)
    op.create_index(op.f('ix_events_project_id'), 'events', ['project_id'], unique=False)
    op.create_index('ix_events_project_id_timestamp', 'events', ['project_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_events_source_id'), 'events', ['source_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('time_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('group_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('source_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("incidents.severity IN ('high', 'medium', 'low')", name=op.f('ck_incidents_incident_severity')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_incidents_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_run_id'], ['agent_runs.id'], name=op.f('fk_incidents_source_run_id_agent_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_project_id'), 'incidents', ['project_id'], unique=False)
    op.create_index(op.f('ix_incidents_source_run_id'), 'incidents', ['source_run_id'], unique=False)
    op.create_index(op.f('ix_incidents_time_start'), 'incidents', ['time_start'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("insights.severity IN ('high', 'medium', 'low')", name=op.f('ck_insights_insight_severity')),
    sa.CheckConstraint("type IN ('fact', 'inference', 'possibility')", name=op.f('ck_insights_insight_type')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_insights_insight_confidence')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_insights_incident_id_incidents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_insights_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_insights_run_id_agent_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insights'))
    )
    op.create_index(op.f('ix_insights_incident_id'), 'insights', ['incident_id'], unique=False)
    op.create_index(op.f('ix_insights_project_id'), 'insights', ['project_id'], unique=False)
    op.create_index(op.f('ix_insights_run_id'), 'insights', ['run_id'], unique=False)
    op.create_table('evidences',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('insight_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('event_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_range', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculation', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], name=op.f('fk_evidences_insight_id_insights'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_evidences_source_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidences'))
    )
    op.create_index(op.f('ix_evidences_insight_id'), 'evidences', ['insight_id'], unique=False)
    op.create_index(op.f('ix_evidences_source_id'), 'evidences', ['source_id'], unique=False)

    # --- Deferred circular FK: events.incident_id -> incidents.id -------------
    # Event and Incident reference each other, so this constraint cannot live in
    # op.create_table('events', ...): `incidents` does not exist yet at that point.
    #
    # SQLAlchemy's `use_alter=True` would defer it under metadata.create_all(), but
    # Alembic's op.create_table() IGNORES use_alter and would silently drop the
    # constraint. It is therefore written out explicitly here, after the last
    # referencing table exists. The model keeps use_alter=True to document intent.
    op.create_foreign_key(
        'fk_events_incident_id_incidents',
        'events',
        'incidents',
        ['incident_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the deferred circular FK first: it depends on `incidents`, which is
    # removed further down. (Postgres would refuse the table drop otherwise.)
    # IF EXISTS keeps this reversible even for databases migrated by the earlier
    # revision that omitted this constraint.
    op.execute(
        'ALTER TABLE events DROP CONSTRAINT IF EXISTS fk_events_incident_id_incidents'
    )
    op.drop_index(op.f('ix_evidences_source_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_insight_id'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_insights_run_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_project_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_incident_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_incidents_time_start'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_source_run_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_project_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_events_source_id'), table_name='events')
    op.drop_index('ix_events_project_id_timestamp', table_name='events')
    op.drop_index(op.f('ix_events_project_id'), table_name='events')
    op.drop_index(op.f('ix_events_incident_id'), table_name='events')
    op.drop_index(op.f('ix_events_group_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_event_groups_time_start'), table_name='event_groups')
    op.drop_index(op.f('ix_event_groups_source_id'), table_name='event_groups')
    op.drop_index(op.f('ix_event_groups_project_id'), table_name='event_groups')
    op.drop_table('event_groups')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_source_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_project_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_parent_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_idempotency_key'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_data_sources_project_id'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###