"""stage08_add_cancel_requested

Revision ID: 1228560be2d2
Revises: 080803e99048
Create Date: 2026-09-23 20:28:49.382385

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '1228560be2d2'
down_revision: str | None = '080803e99048'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('cancel_requested', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'cancel_requested')
    # ### end Alembic commands ###